### ISSUE TITLE
Nix integration: "Unable to find Composer" even if present

### ISSUE THREAD

**Issue by mykiwi** [symfony-cli/symfony-cli#123]
Hi

I recently tried [Replit](https://replit.com), it is like [GitHub Codespaces](https://github.com/features/codespaces) but with nix behind to handle packages.
So I tried to install `php`, `composer` & `symfony-cli` with nix to create a new Symfony project, and I saw this:
```
$ symfony-cli new foo
* Creating a new Symfony project with Composer
  WARNING: Unable to find Composer, downloading one. It is recommended to install Composer yourself at https://getcomposer.org/download/
...


$ # so I tried to understand why
$ whereis composer
composer: /nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6/bin/composer


$ echo $PATH | tr E':' '\n'
...
/nix/store/6ni9a0gkfscic4bq8l376xza2zf874y9-php-with-extensions-8.1.3/bin
/nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6/bin
/nix/store/x9ja3hf9plylx9rpaqy9wd2f5j60wy26-symfony-cli-5.3.4/bin
...


$ cat /nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6/bin/composer
#! /nix/store/4nmqxajzaf60yjribkgvj5j54x9yvr1r-bash-5.1-p12/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/64kd7qghqw3j0wqbss7shm3ad3awbsis-unzip-6.0/bin'':'/':'}
PATH='/nix/store/64kd7qghqw3j0wqbss7shm3ad3awbsis-unzip-6.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
exec "/nix/store/6ni9a0gkfscic4bq8l376xza2zf874y9-php-with-extensions-8.1.3/bin/php"  /nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6/libexec/composer/composer.phar "$@"
```

The warning is triggered because we check if the `composer` file starts with this shebang:
https://github.com/symfony-cli/symfony-cli/blob/54ff09da1ab7085262f0dfef7c97ea8d0ea76423/local/php/composer.go#L98-L111

based on the comment on top of the function, should we do the opposite to fix this (checking if this is a bat file)?

---

To reproduce: https://replit.com/@mykiwi/reproduce-symfony-cli-warning and hit "Run"

**Comment by fabpot** [comment]
Can you submit a PR?

**Comment by tucksaun** [comment]
Actually that won't work: the CLI will try to go through the executor.
It means it will try to run basically similar to `php /nix/store/grm58racabmyxakvp1axlb4r6b8icvfj-php-composer-2.2.6/bin/composer` which should not work because this is a shell script not a PHP one).

**Comment by mykiwi** [comment]
A simple fix would be to check if there is a shebang, like this:
```diff
- magicPrefix := []byte("#!/usr/bin/env php") 
+ magicPrefix := []byte("#!")
```

Do you think this is enough? if yes I can create the PR

**Comment by tucksaun** [comment]
You can try but I don't think it will work because it means the CLI will try to execute the shell wrapper created by Nix by using PHP but PHP doesn't know how to execute a shell script.

I think there are three solutions here:
1. When a `composer` file is found but is not a PHP script, fallback to executing the script directly if it is executable. The drawback is that it disables the PHP version selection done by the CLI
2. Try to detect the composer.phar and execute it directly as currently done for composer scripts, through it means try to find
3. I'm not familiar enough with Nix but how does one manage multiple versions of PHP? Does it actually makes sense to use the CLI in this context?

@fabpot any thought about this? depending on what you prefer I can help @mykiwi to implement it.

**Comment by fabpot** [comment]
3 is interesting but I think the answer is when you want to use the CLI web server.
I think 2 is the best way to go... if possible :) Probably "doing our best"

**Comment by tucksaun** [comment]
@fabpot @mykiwi see #132 for a possible solution
