### ISSUE TITLE
Executable composer.phar in the current directory is not honored?

### ISSUE THREAD

**Issue by gremo** [symfony-cli/symfony-cli#150]
Windows 10 x64, Symfony CLI v5.4.10, global composer v1.x, local composer.phar 2.x.

Output of `symfony php composer.phar -v`:

```
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /    
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/     
                    /_/
Composer version 2.3.7 2022-06-06 16:43:28
```

However, `symfony composer -v`:

```
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.10.25 2022-01-21 10:02:15
```

Why? Is this supposed to work that way? The documentation:

> For [Symfony CLI](https://symfony.com/doc/current/setup/symfony_server.html), running symfony composer checks the version of 
Composer used in the composer.lock file and tries to find a Composer binary named composer1 or composer2. If it fails, it falls back to the regular composer.phar or composer file names. The binary can be in the current directory or in the $PATH.

**Comment by tucksaun** [comment]
IMO this should be considered as a bug as we explicitly launch the code to detect the current context to launch the right Composer version here: https://github.com/symfony-cli/symfony-cli/blob/6049a7be3c2df8ab5f0a8f18c101db28b39493d3/local/php/executor.go#L272

The bug is probably related to the fact that `executor.Config` is expecting the args to be provided to process the configuration, which is not possible in the case of the composer detection as we need the composer path to build the args list: https://github.com/symfony-cli/symfony-cli/blob/6049a7be3c2df8ab5f0a8f18c101db28b39493d3/local/php/composer.go

to fix this bug we can force only the scriptDir detection instead of start the full executor configuration when trying to find Composer (it looks like the script dir is the only thing used here). wdyt @fabpot ?

**Comment by tucksaun** [comment]
See #165 for a possible fix
