### ISSUE TITLE
After close symfony:serve, can't run it correctly

### ISSUE THREAD

**Issue by gbere** [symfony-cli/symfony-cli#18]
After close symfony:serve, can't run it correctly.

But if change the PHP version on .php-version or delete the ~/.symfony5/var/xxxx/xxxx.pid it's running well

**Comment by j4nr6n** [comment]
@gbere Is there an error message?

**Comment by janklan** [comment]
I've got the same problem, so I'll try to add some more info to this:

* Symfony CLI version 5.0.7 (c) 2017-2022 Symfony SAS (2022-01-03T09:39:22Z - stable)
* PHP 8.0.13 (cli) (built: Nov 28 2021 13:11:14) ( NTS )
* macOS 12.1 @ M1
* The CLI works once, but consecutive starts fail to launch php-fpm - the only output is an info that the server is tailing two log files and then the process just hangs there
* The only error I can see is `{"level":"error","message":"Unable to start PHP-FPM"}` when I hit `^C`
* Removing the PID file (like @gbere) said solves the problem, once - the PID file must be removed every time in order to start the server

I'm not sure if this is relevant, but:

* I had no issues with the manually installed v4 version. I removed the file and used homebrew to install v5, which is where the problem started
* Every time I start the binary, my firewall is asking me whether I want to allow incoming connections. This has not been happening with the previous version. Most likely irrelevant, though.

Here is my entire console command capturing a failed start, removal of the PID file, and consecutive restart. 

```
janklan@pb app % symfony serve
Tailing Web Server log file (/Users/janklan/.symfony5/log/7240ac7dcb5ca7abcc6cecd516f3f01a5ceca0ca.log)
Tailing PHP-FPM log file (/Users/janklan/.symfony5/log/7240ac7dcb5ca7abcc6cecd516f3f01a5ceca0ca/53fb8ec204547646acb3461995e4da5a54cc7575.log)
^C{"level":"error","message":"Unable to start PHP-FPM"}
                                                                                                                        
 [ERROR] PHP-FPM failed to start:                                                                                       
 fpm is running, pid 2648                                                                                               
 ready to handle connections                                                                                            
 Terminating ...                                                                                                        
                                                                                                                        
janklan@pb app % rm ~/.symfony5/var/7240ac7dcb5ca7abcc6cecd516f3f01a5ceca0ca/eae5a91f67e6ab516cf766bd2eebd5e4b5dfd1be.pid
janklan@pb app % symfony serve                                                                                           
Tailing Web Server log file (/Users/janklan/.symfony5/log/7240ac7dcb5ca7abcc6cecd516f3f01a5ceca0ca.log)
Tailing PHP-FPM log file (/Users/janklan/.symfony5/log/7240ac7dcb5ca7abcc6cecd516f3f01a5ceca0ca/53fb8ec204547646acb3461995e4da5a54cc7575.log)
                                                                                                                        
 [OK] Web server listening                                                                                              
      The Web server is using PHP FPM 8.0.13                                                                            
      https://127.0.0.1:8000                                                                                            
                                                                                                                        

[Web Server ] Jan  4 10:20:17 |DEBUG  | PHP    Reloading PHP versions 
[Web Server ] Jan  4 10:20:17 |DEBUG  | PHP    Using PHP version 8.0.13 (from .php-version from current dir: /Users/janklan/dev/foo/.php-version) 
```

**Comment by fabpot** [comment]
I can reproduce the problem on macOS. I even found that this is caused by the fact we are using disabling CGO in the release process via `CGO_ENABLED=0`. When running with CGO enabled, everything works as expected.
