### ISSUE TITLE
Add Kibana to toolbar if detected by Docker integration?

### ISSUE THREAD

**Issue by jmsche** [symfony-cli/symfony-cli#197]
Hi,

I'm wondering if it is possible to add Kibana in the toolbar if it's detected by Docker integration?

It would be nice as Elasticsearch is already handled by the CLI :)

**Comment by jmsche** [comment]
Also maybe add a `open:local:kibana` command at the same time if it is accepted :)

**Comment by tucksaun** [comment]
For reference, official Kibana image uses port 5601.

I like the idea.

I would even go further: 
Why not add links to every http relationship found so that if we add more this will be handled automatically?
For commands we could do the same and `open:local:webmail` and `open:local:rabbitmq` would become `open:local:service mailer` and `open:local:service rabbitmq`.
And for you usecase `open:local:service kibana`?

**Comment by jmsche** [comment]
Sure, that would be great :) 

Unfortunately my knowlegde of Go language is quite equal to 0 :/

**Comment by tucksaun** [comment]
I should be able to have a look in two weeks time.

@fabpot are you pleased with the `open:local:service xxx` suggestion?

**Comment by fabpot** [comment]
I like this proposal. `xxx` would be the service name to allow for more than one service of the same kind?

**Comment by tucksaun** [comment]
I had in mind to use the `rel` but yes we could use the service name instead that would make more sense.

Maybe we could first find by service name and fall back to `rel` if the service is not found by name?

**Comment by mwansinck** [comment]
We are switching from our custom docker setup with custom tools (built on top of phpdeployer) to Symfony CLI. 
However the problem described in this issue is a problem for us. When running multiple project and using random ports for those services there is no easy way to access web based user interfaces for containers like phpMyAdmin, Adminer, Elasticsearch and others.

Because I am not a Go developer, I can't contribute to help out within Symfony CLI, so I created a solution as a Symfony Bundle by extending the developer toolbar and re-using the environment variables created by Symfony CLI.

<img width="314" alt="docker-toolbar" src="https://user-images.githubusercontent.com/11411864/214397284-25183aa2-a4b4-4a14-949a-12e7fb54eea6.png">

Feel free to try it out;
https://packagist.org/packages/webstack/docker-toolbar-bundle

**Comment by tucksaun** [comment]
So it ended up taking a bit more time than anticipated 😅
But here we are, see #261, #263 and #264

**Comment by mwansinck** [comment]
@tucksaun Is it possible to implement support for non-usual http/https ports also (for example 8000, 8080, 8443, or even more exotic). Some containers use other ports numbers for there web ui's. Maybe configurable by docker labels to force the scheme.

**Comment by tucksaun** [comment]
@mwansinck 8080 and 8443 are supported (see #262)
but we can't make treat every port as HTTP neither.
Having labels to force the schemes is indeed something I had in mind while implementing #262 but I didn't explore it so far
