### ISSUE TITLE
Symfony-cli .deb repo stopped udpates to v5.4.13

### ISSUE THREAD

**Issue by matracine** [symfony-cli/symfony-cli#201]
Hello,
I'm using  https://repo.symfony.com/apt/ to have Symfony CLI up-to-date on Ubuntu.
This repo does not seem to have latests versions (5.4.14, 5.4.15 and 5.4.16).
Do you plan to update the repo ?
Thanks,

**Comment by tucksaun** [comment]
In order to provide support for signed packages packages hosting has been migrated to another provider (see https://github.com/symfony-cli/symfony-cli/pull/151 and https://github.com/symfony-cli/symfony-cli/pull/172).

In order to migrate you will need to:
1. Remove /etc/apt/sources.list.d/symfony-cli.list
2. Follow the new instructions: https://symfony.com/download

**Comment by matracine** [comment]
Thanks !
