### ISSUE TITLE
Unable to download https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh

### ISSUE THREAD

**Issue by Ceslav** [symfony-cli/symfony-cli#205]
I'm trying to [install symfony cli on Ubuntu](https://symfony.com/download), but https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh returns 402 status code

**Comment by naderman** [comment]
```
Err https://dl.cloudsmith.io/public/symfony/stable/deb/ubuntu focal InRelease                                                          
  402  Payment Required [IP: 18.64.79.121 443]
```

Looks like the cloudsmith account was disabled for non-payment?

**Comment by shyim** [comment]
For OSS you get only 200 GB Bandwidth at Cloudsmith. Maybe that is already over?

**Comment by fabpot** [comment]
Unfortunately, we went over the OSS bandwidth this month (the growth has been very important durant the last 4 months). I'm working with Cloudsmith to figure out a long-term solution. Hopefully, we will be back very soon.

**Comment by tucksaun** [comment]
@fabpot do you believe most of the bandwidth usage could be related to Dockerfiles built over and over again?

If that is the case, maybe we can deliver a simple Docker image published on Docker Hub that one can use to `COPY` from instead of using the package manager?

**Comment by curry684** [comment]
It would make more sense to provide a separate installer script for all scripted access, including CI and Dockerfiles. The current scripts always install through package manager, which is awesome to automatically get updates on developer machines, but which is practically useless in CI/Docker scenarios. I only need/use the script because there is no permalink to the latest release on Github, if there was something like `https://download.symfony.com/symfony-cli/debian/latest.deb` with a redirect to the latest package I could just script that instead.

**Comment by tucksaun** [comment]
@curry684 there's already one script (that should support most Linux distros) available at https://get.symfony.com/cli/installer

One can also directly downloads the latest binary at the permalink `https://github.com/symfony-cli/symfony-cli/releases/latest/download/symfony-cli_<platform>.tar.gz`  (replacing `<platform>` with the appropriate platform you are running on).

But both approaches in Docker have issues with caching, that's why I'm suggesting releasing a Docker image which looks like a more idiomatic way in that specific case.

**Comment by fabpot** [comment]
I think it makes sense @tucksaun. CIs/bots/... in general are a big pain for bandwidth. That's why we stopped having a security checker server. It was 90% of bots doing stupid things and nobody cares about the output anyway. So depressing.

**Comment by tucksaun** [comment]
IIRC GoReleaser supports Dockerfile so this should be fairly easy to install (and I should have some time soon to take care of it if you need to) but Docker Hub is now based on paid subscriptions as well so you would have to apply for a free OSS plan.

Or we could use GitHub packages which should be free for public packages

**Comment by shyim** [comment]
.goreleaser.yml
```
dockers:
  - image_templates:
      - "ghcr.io/symfony-cli/symfony-cli:{{ .Tag }}"
      - "ghcr.io/symfony-cli/symfony-cli:v{{ .Major }}"
      - "ghcr.io/symfony-cli/symfony-cli:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/symfony-cli/symfony-cli:latest"
```

Dockerfile

```yaml
FROM scratch
COPY symfony-cli /usr/local/bin/
```

it should work then 🤔

**Comment by fabpot** [comment]
I would use GitHub packages to have everything in one place :)
If you can work on it @tucksaun, that would be awesome.

**Comment by curry684** [comment]
> there's already one script (that should support most Linux distros) available at https://get.symfony.com/cli/installer

It would be a good idea to have that documented at https://symfony.com/download 😉

**Comment by tucksaun** [comment]
@curry684 nice idea. We will need to kindly ask @javiereguiluz or @fabpot :)
But I think it would be nice to do a single change and wait for the Docker image to be ready

**Comment by fabpot** [comment]
@curry684 Added the installer option on the https://symfony.com/download page.

![image](https://user-images.githubusercontent.com/47313/199180370-8807aded-8d0c-4d33-a5f7-79aaaa29ff1b.png)

**Comment by shyim** [comment]
@fabpot should we add an example to install globally? (I hate adjusting my path)

```
wget https://get.symfony.com/cli/installer -O - | sudo bash -s -- --install-dir=/usr/bin/symfony
```

**Comment by fabpot** [comment]
The Cloudsmith issue is now resolved.

**Comment by fabpot** [comment]
The Cloudsmith issue is now resolved.

**Comment by tucksaun** [comment]
@jadeops regarding auto-updates: we used to have this in v3 and v4

But this is not as easy to do in Go as it is in PHP and there were tons of small edge cases that were not easy to tackle.
Support for auto-updates has been dropped in v5 and the CLI is now mostly released via package managers so I don't see the need for support auto-updates anymore.
