### ISSUE TITLE
Error SEC_ERROR_UNKNOWN_ISSUER after installed certificate

### ISSUE THREAD

**Issue by gundesli** [symfony-cli/symfony-cli#291]
I'm the problem with certificate.

I have enabled TLS with this command : 

`symfony server:ca:install`

I get the following result :

```
The local CA is now installed in the system trust store!
The local CA is now installed in the Firefox and/or Chrome/Chromium trust store (requires browser restart)!
Generating a default certificate for HTTPS support
[OK] The local Certificate Authority is installed and trusted
```

I launch server with symfony cli, the server start but when i go on Firefox (https://127.0.0.1:8000) i have this error :

`SEC_ERROR_UNKNOWN_ISSUER`

It worked before.
I uninstalled the certificate and then reinstalled it.
I restarted my computer and I still have the same problem.
The problem persist.

- OS : Ubuntu 22.04.2 LTS
- symfony cli : 5.5.1
- Firefox : 110.0.1 installed natively with snap

**Comment by tucksaun** [comment]
IIRC Firefox has its own cert store and the cert library (https://github.com/symfony-cli/cert) has to hook into the local Firefox installation to inject the certificate to the store.

We probably don't detect any snap Firefox installation because snap are kind of isolated path-wise.
I don't have any system with Snap available at the moment so could you check the paths for your firefox snap and see if they could be updated here: https://github.com/symfony-cli/cert/blob/main/truststore_nss.go#L14-L29

Thanks!

**Comment by gundesli** [comment]
Here is the path for Firefox snap on Ubuntu 22.04 LTS:

`home/snap/firefox/current`

As for Chromium snap version : https://github.com/symfony-cli/cert/blob/main/truststore_nss.go#L16

You should probably add :

`filepath.Join(os.Getenv("HOME"), "snap/firefox/current/.pki/nssdb"), // Snapcraft`
