### ISSUE TITLE
ReverseProxy error starting from v5.7.1

### ISSUE THREAD

**Issue by Herz3h** [symfony-cli/symfony-cli#381]
Since version v5.7.1 I'm getting an error with the server cli, it shows the following error:

```
httputil: ReverseProxy read error during body copy: fcgi: invalid header version
```

Doesn't matter which page, or which browser I'm using. Tried removing the CA certificate and it does the same in http aswell. 

I'm using php 7.4.33 and symfony 5.4 on OSx Ventura. CLI installed using the curl script from the docs.

I have to downgrade to a lower version for it to stop throwing that error. Let me know if there is more infos I can provide for further debug.

**Comment by fabpot** [comment]
@tucksaun Maybe related to the changes you've made recently?

**Comment by tucksaun** [comment]
@fabpot might be indeed but for now I don't have any clue why 🤷 

@Herz3h do you have any additional logs available? could you also let me know if you are using CGI or FPM? thanks!

**Comment by Herz3h** [comment]
@tucksaun Don't know how I could you provide you with more logs. The only thing logged in the console is the line in the initial post. Let me know if there is any way i could give you more details.

Using FPM (listening path="/opt/homebrew/Cellar/php@7.4/7.4.33_5/sbin/php-fpm")

**Comment by smnandre** [comment]
Massive drop in performances since a couple of days too.
Interestingly it occurs only with Firefox and  the local:proxy started

Nothing in the logs, except many requests take up to 20 seconds (instead of the usual 100ms) 

macOS Sonoma 14.0
Apple M1
PHP 8.1 / 8.2 / 8.3  (php-fpm / brew)
symfony-cli 5.7.3

I'll update macOS tomorrow, maybe the available bugfix update solves things.

**Comment by smnandre** [comment]
No positive change after macOS update. Some requests can wait up to minutes... 

Well i'm having hard time to isolate a "single" reason (AssetMapper ? Symfony Cli ? Firefox ? macOS ?) 

### Something with HTTPS / ports ?

BUT it's now clear for me there is something weird with either the HTTPS/proxy or the ports 
(--no-tls seems to fix the problem with Firefox)

I'll retry on new projects to bring you more details.


### 🐾  Maybe something there

I don't know if related but the only suspect thing i saw on the logs was this `de_` instead of "dev" on the cache path

`[Application] Nov 19 12:56:56 |DEBUG  | PHP    Warning: filemtime(): stat failed for /Users/simonandre/Sites/symfony/ux/ux.symfony.com/var/cache/de_/App_KernelDevDebugContainer.php
`

**Comment by tucksaun** [comment]
@smnandre I dont think your problem is related to this issue because a CGI communication error as mentioned in the description would lead to no page being served at all.

The fact that you have errors during Symfony cache build makes me believe this a possible cause for the bad performance you experience

**Comment by smnandre** [comment]
> @smnandre I dont think your problem is related to this issue because a CGI communication error as mentioned in the description would lead to no page being served at all.
> 
> The fact that you have errors during Symfony cache build makes me believe this a possible cause for the bad performance you experience

You're right, i edited my comments to un-pollute this thread (sorry for the noise) and i'll post another once i'm sure off the causes.

**Comment by tucksaun** [comment]
@Herz3h unfortunately I don't manage to reproduce your issue :( 
>  debug-381 $ symfony version
> Symfony CLI version 5.7.3 (c) 2021-2023 Fabien Potencier (2023-11-14T09:01:20Z - stable)
>  debug-381 $ symfony serve
> Following Web Server log file (/Users/tucksaun/.symfony5/log/631d33ada1a9ec637d883f54456c6bc3ea51afd1.log)
> Following PHP-FPM log file (/Users/tucksaun/.symfony5/log/631d33ada1a9ec637d883f54456c6bc3ea51afd1/53fb8ec204547646acb3461995e4da5a54cc7575.log)
> 
>  [WARNING] The local web server is optimized for local development and MUST never be used in a production setup.
> 
> 
> 
>  [OK] Web server listening
>       The Web server is using PHP FPM 7.4.33
>       https://127.0.0.1:8001
>       https://foo.wip
> 
> 
> [Web Server ] Nov 20 17:24:55 |DEBUG  | PHP    Reloading PHP versions
> [Web Server ] Nov 20 17:24:55 |DEBUG  | PHP    Using PHP version 7.4.33 (from .php-version from current dir: /private/tmp/debug-381/.php-version)
> [Web Server ] Nov 20 17:24:55 |INFO   | PHP    listening path="/opt/homebrew/Cellar/php@7.4/7.4.33_5/sbin/php-fpm" php="7.4.33" port=60092
> [PHP-FPM    ] Nov 20 17:24:55 |NOTICE | FPM    fpm is running, pid 61210
> [PHP-FPM    ] Nov 20 17:24:55 |NOTICE | FPM    ready to handle connections
> [Web Server ] Nov 20 17:25:00 |INFO   | SERVER GET  (200) / ip="127.0.0.1"
> [Web Server ] Nov 20 17:25:00 |INFO   | SERVER GET  (200) /favicon.ico
> [Web Server ] Nov 20 17:25:00 |INFO   | SERVER GET  (200) /
> [Web Server ] Nov 20 17:25:00 |INFO   | SERVER GET  (200) /favicon.ico
> [Web Server ] Nov 20 17:25:01 |INFO   | SERVER GET  (200) /
> [Web Server ] Nov 20 17:25:01 |INFO   | SERVER GET  (200) /favicon.ico
> [Web Server ] Nov 20 17:25:01 |INFO   | SERVER GET  (200) /
> [Web Server ] Nov 20 17:25:01 |INFO   | SERVER GET  (200) /favicon.ico
> [Web Server ] Nov 20 17:25:02 |INFO   | SERVER GET  (200) /
> [Web Server ] Nov 20 17:25:02 |INFO   | SERVER GET  (200) /favicon.ico

Can you try to run `symfony serve -v=5`? maybe we'll see something in the logs

**Comment by tucksaun** [comment]
@smnandre you might be interested to have a look at https://github.com/symfony-cli/symfony-cli/issues/363 and see if that matches your issue

**Comment by smnandre** [comment]
So it was related. But why is still unclear.

**Comment by smnandre** [comment]
Is it _possible_ all this is related to [those changes](https://github.com/symfony-cli/symfony-cli/commit/529f67c92b030af5761a633f5130513b280c9169) (just in case, my knowledges in GO stop at knowing it's a language :))
